/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import com.squareup.moshi.Json
import java.time.LocalDate
import java.time.LocalDateTime

/**
 *
 * @param id The unique identifier for the applicant. Read-only.
 * @param createdAt The date and time when this applicant was created. Read-only.
 * @param deleteAt The date and time when this applicant is scheduled to be deleted. Read-only.
 * @param href The uri of this resource. Read-only.
 * @param sandbox Read-only.
 * @param title The applicant’s title
 * @param firstName The applicant’s first name
 * @param middleName The applicant’s middle name(s) or initial
 * @param lastName The applicant’s surname
 * @param email The applicant’s email address. Required if doing a US check or a standard UK check.
 * @param gender The applicant’s gender. Valid values are male and female.
 * @param dob The applicant’s date of birth
 * @param telephone The applicant’s landline phone number
 * @param mobile The applicant’s mobile phone number
 * @param country The country where this applicant will be checked. This must be a three-letter ISO code e.g. GBR or USA
 * @param nationality The applicant's nationality. This must be a three-letter ISO code e.g. GBR or USA
 * @param mothersMaidenName The applicant’s mothers maiden name
 * @param countryOfBirth The applicant’s country of birth
 * @param townOfBirth The applicant’s town of birth
 * @param previousLastName The applicant’s previous last name
 * @param addresses
 * @param idNumbers
 */

data class Applicant(
        val id: String? = null,

        @field:Json(name = "created_at")
        val createdAt: LocalDateTime? = null,

        @field:Json(name = "deleted_at")
        val deleteAt: LocalDateTime? = null,
        val href: String? = null,
        val sandbox: kotlin.Boolean?,
        val title: kotlin.String?,

        @field:Json(name = "first_name")
        val firstName: kotlin.String,

        @field:Json(name = "middle_name")
        val middleName: String?,

        @field:Json(name = "last_name")
        val lastName: kotlin.String? = null,

        val email: kotlin.String? = null,
        val gender: kotlin.String? = null,
        val dob: String? = null,
        val telephone: kotlin.String? = null,
        val mobile: kotlin.String? = null,
        val country: kotlin.String? = null,
        val nationality: kotlin.String? = null,

        @field:Json(name = "mothers_maiden_name")
        val mothersMaidenName: kotlin.String? = null,

        @field:Json(name = "country_of_birth")
        val countryOfBirth: kotlin.String? = null,

        val townOfBirth: kotlin.String? = null,

        @field:Json(name = "previous_last_name")
        val previousLastName: String? = null,

        val addresses: kotlin.Array<Address>? = null,

        @field:Json(name = "id_numbers")
        val idNumbers: kotlin.Array<IdNumber>? = null
) {

}

