/**
* Onfido API
* The Onfido API is used to submit check requests.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param id The unique identifier for the document
 * @param createdAt The date and time at which the document was uploaded
 * @param fileName The name of the uploaded file
 * @param fileSize The size of the file in bytes
 * @param fileType The file type of the uploaded file
 * @param type The type of document
 * @param side The side of the document, if applicable. The possible values are front and back
 * @param href The uri of this resource
 * @param downloadHref The uri that can be used to download the document
 */
data class Document (
    /* The unique identifier for the document */
    val id: kotlin.String? = null,
    /* The date and time at which the document was uploaded */
    val createdAt: java.time.LocalDateTime? = null,
    /* The name of the uploaded file */
    val fileName: kotlin.String? = null,
    /* The size of the file in bytes */
    val fileSize: kotlin.Int? = null,
    /* The file type of the uploaded file */
    val fileType: kotlin.String? = null,
    /* The type of document */
    val type: kotlin.String? = null,
    /* The side of the document, if applicable. The possible values are front and back */
    val side: kotlin.String? = null,
    /* The uri of this resource */
    val href: kotlin.String? = null,
    /* The uri that can be used to download the document */
    val downloadHref: kotlin.String? = null
) {

}

