/**
* Onfido API
* The Onfido API is used to submit check requests.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param id 
 * @param type 
 * @param message 
 * @param fields 
 */
data class Error (
    val id: kotlin.String? = null,
    val type: kotlin.String? = null,
    val message: kotlin.String? = null,
    val fields: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null
) {

}

