/**
* Onfido API
* The Onfido API is used to submit check requests.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param flatNumber The flat number of this address
 * @param buildingNumber The building number of this address
 * @param buildingName The building name of this address
 * @param street The street of the applicant’s address
 * @param subStreet The sub-street of the applicant’s address
 * @param town The town of the applicant’s address
 * @param postcode The postcode or ZIP of the applicant’s address
 * @param country The 3 character ISO country code of this address. For example, GBR is the country code for the United Kingdom
 */
data class GenericAddress (
    /* The flat number of this address */
    val flatNumber: kotlin.String? = null,
    /* The building number of this address */
    val buildingNumber: kotlin.String? = null,
    /* The building name of this address */
    val buildingName: kotlin.String? = null,
    /* The street of the applicant’s address */
    val street: kotlin.String? = null,
    /* The sub-street of the applicant’s address */
    val subStreet: kotlin.String? = null,
    /* The town of the applicant’s address */
    val town: kotlin.String? = null,
    /* The postcode or ZIP of the applicant’s address */
    val postcode: kotlin.String? = null,
    /* The 3 character ISO country code of this address. For example, GBR is the country code for the United Kingdom */
    val country: kotlin.String? = null
) {

}

