/**
* Onfido API
* The Onfido API is used to submit check requests.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param type Type of ID number. Valid values are `ssn`, `social_insurance`, `tax_id`, `identity_card`, `passport` and `driving_license`
 * @param value Value of ID number
 * @param stateCode Two letter code of issuing state (state-issued driving licenses only)
 */
data class IdNumber (
    /* Type of ID number. Valid values are `ssn`, `social_insurance`, `tax_id`, `identity_card`, `passport` and `driving_license` */
    val type: kotlin.String? = null,
    /* Value of ID number */
    val value: kotlin.String? = null,
    /* Two letter code of issuing state (state-issued driving licenses only) */
    val stateCode: kotlin.String? = null
) {

}

