/**
* Onfido API
* The Onfido API is used to submit check requests.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param type The type of document.
 * @param side Either the `front` or `back` of the document.
 * @param file The file to be uploaded.
 */
data class InlineObject (
    /* The type of document. */
    val type: kotlin.String,
    /* The file to be uploaded. */
    val file: java.io.File,
    /* Either the `front` or `back` of the document. */
    val side: kotlin.String? = null
) {

}

