/**
* Onfido API
* The Onfido API is used to submit check requests.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.LiveVideo

/**
 * 
 * @param liveVideos 
 */
data class LiveVideosList (
    val liveVideos: kotlin.Array<LiveVideo>? = null
) {

}

