/**
* Onfido API
* The Onfido API is used to submit check requests.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ReportDocument
import org.openapitools.client.models.ReportOption

/**
 * 
 * @param id The unique identifier for the report. Read-only.
 * @param createdAt The date and time at which the report was first initiated. Read-only.
 * @param href The API endpoint to retrieve the report. Read-only.
 * @param status The current state of the report in the checking process. Read-only.
 * @param result The result of the report. Read-only.
 * @param subResult The sub_result of the report. It gives a more detailed result for document reports only, and will be null otherwise. Read-only.
 * @param breakdown The details of the report. This is specific to each type of report. Read-only.
 * @param properties The properties associated with the report, if any. Read-only.
 * @param name The name of the report type.
 * @param variant The name of the report type variant, if required.
 * @param options List of Report Option objects.
 * @param documents Array of objects with document ids that were used in the Onfido engine. [ONLY USED IN A DOCUMENT CHECK]
 */
data class Report (
    /* The name of the report type. */
    val name: kotlin.String,
    /* The unique identifier for the report. Read-only. */
    val id: kotlin.String? = null,
    /* The date and time at which the report was first initiated. Read-only. */
    val createdAt: java.time.LocalDateTime? = null,
    /* The API endpoint to retrieve the report. Read-only. */
    val href: kotlin.String? = null,
    /* The current state of the report in the checking process. Read-only. */
    val status: kotlin.String? = null,
    /* The result of the report. Read-only. */
    val result: kotlin.String? = null,
    /* The sub_result of the report. It gives a more detailed result for document reports only, and will be null otherwise. Read-only. */
    val subResult: kotlin.String? = null,
    /* The details of the report. This is specific to each type of report. Read-only. */
    val breakdown: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    /* The properties associated with the report, if any. Read-only. */
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    /* The name of the report type variant, if required. */
    val variant: kotlin.String? = null,
    /* List of Report Option objects. */
    val options: kotlin.Array<ReportOption>? = null,
    /* Array of objects with document ids that were used in the Onfido engine. [ONLY USED IN A DOCUMENT CHECK] */
    val documents: kotlin.Array<ReportDocument>? = null
) {

}

