/**
* Onfido API
* The Onfido API is used to submit check requests.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ReportOption

/**
 * 
 * @param id 
 * @param name 
 * @param variant 
 * @param options 
 */
data class ReportType (
    val id: kotlin.String? = null,
    val name: kotlin.String? = null,
    val variant: kotlin.String? = null,
    val options: kotlin.Array<ReportOption>? = null
) {

}

