/**
* Onfido API
* The Onfido API is used to submit check requests.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ReportType

/**
 * 
 * @param id The unique identifier for the group.
 * @param name The group’s name, as specified under your account.
 * @param groupOnly If false, individual reports in that group can be requested; if true, all reports must be requested together.
 * @param reportTypes A list of report types included in this group.
 */
data class ReportTypeGroup (
    /* The unique identifier for the group. */
    val id: kotlin.String? = null,
    /* The group’s name, as specified under your account. */
    val name: kotlin.String? = null,
    /* If false, individual reports in that group can be requested; if true, all reports must be requested together. */
    val groupOnly: kotlin.Boolean? = null,
    /* A list of report types included in this group. */
    val reportTypes: kotlin.Array<ReportType>? = null
) {

}

